// <auto-generated />
using System;
using HumanRegisterWebApi.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HumanRegisterWebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HumanRegisterWebApi.Models.ProfileImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("ImageBytes")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid?>("UserInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserInfoId")
                        .IsUnique()
                        .HasFilter("[UserInfoId] IS NOT NULL");

                    b.ToTable("ProfileImage");
                });

            modelBuilder.Entity("HumanRegisterWebApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HumanRegisterWebApi.Models.UserAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ApartamentNumber")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("HouseNmber")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("UserInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserInfoId")
                        .IsUnique()
                        .HasFilter("[UserInfoId] IS NOT NULL");

                    b.ToTable("UserAddreses");
                });

            modelBuilder.Entity("HumanRegisterWebApi.Models.UserInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("PersonCode")
                        .HasMaxLength(11)
                        .HasColumnType("bigint");

                    b.Property<long>("PhoneNumber")
                        .HasMaxLength(12)
                        .HasColumnType("bigint");

                    b.Property<string>("SecName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("UserInfos");
                });

            modelBuilder.Entity("HumanRegisterWebApi.Models.ProfileImage", b =>
                {
                    b.HasOne("HumanRegisterWebApi.Models.UserInfo", "UserInfo")
                        .WithOne("ProfileImage")
                        .HasForeignKey("HumanRegisterWebApi.Models.ProfileImage", "UserInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("HumanRegisterWebApi.Models.UserAddress", b =>
                {
                    b.HasOne("HumanRegisterWebApi.Models.UserInfo", "UserInfo")
                        .WithOne("UserAddress")
                        .HasForeignKey("HumanRegisterWebApi.Models.UserAddress", "UserInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("HumanRegisterWebApi.Models.UserInfo", b =>
                {
                    b.HasOne("HumanRegisterWebApi.Models.User", "User")
                        .WithOne("UserInfo")
                        .HasForeignKey("HumanRegisterWebApi.Models.UserInfo", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("HumanRegisterWebApi.Models.User", b =>
                {
                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("HumanRegisterWebApi.Models.UserInfo", b =>
                {
                    b.Navigation("ProfileImage");

                    b.Navigation("UserAddress");
                });
#pragma warning restore 612, 618
        }
    }
}
